GET /api/v3/urls/NjRmMmFhODZlMTEyMjFhYjk0YmJkOTAwMDBmNTk3YWU6MTY1MDIzNTE2Ng HTTP/1.1
Accept: application/json
X-Apikey: 0884cf2c2e6d77db8a6bf524d38b6aff88ccee7b61cde1621799d63da1958c6e
Host: www.virustotal.com